<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }
    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    tr:nth-child(even) {
        background-color: #dddddd;
    }
    .post-id{
        width:2%
    }
    .post-name{
        width:30%
    }

</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php
    foreach ($block->getCustomerCollection() as $key => $user) {
        echo '<tr>
                    <td>' . $user->getEntityId() . '</td>
                    <td>' . $user->getEmail() . '</td>
                    <td>' . $user->getFirstname() . '</td>
                  </tr>';
    }
    ?>


</table>

<div class="row">
    <div class="col text-center">
        <form action="<?php echo $block->getFormAction() ?>" method="post" autocomplete="off" id="custom-form">
            <div class="form-row">
                <div class="col">
                    <label for="name" class="form-label">Name</label>
                    <input name="name" required type="text" class="form-control" id="name" aria-describedby="emailHelp">
                </div>
                <div class="col">
                    <label class="form-label">URL</label>
                    <input name="url_key" required type="text" class="form-control" id="url_key">
                </div>
                <div class="col">
                    <label class="form-label">Description</label>
                    <input name="post_content" required type="text" class="form-control" id="post_content">
                </div>
                <div class="col">
                    <label class="form-label">Status</label>
                    <select required name="status">
                        <?php
                        foreach ($block->getCustomerCollection() as $key => $customer) {
                            echo "<option value={$customer->getEntityId()}>{$customer->getFirstname()}</option>";
                        }
                        ?>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script type="text/x-magento-init">
    {
    "#custom-form": {
    "validation": {}
    }
    }
</script>
<script  type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>jQuery.noConflict()</script>
<script type="text/javascript">
    //require(["jquery", 'jquery/ui'], function ($) {
    jQuery(document).ready(function () {
        jQuery("#custom-form").submit(function (event) {
            let url = "<?php echo $block->getFormAction() ?>";
            jQuery.ajax({
                url: url,
                type: 'POST',
                dataType: 'json',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                },
                data: jQuery("#custom-form").serialize(),
                complete: function (response) {
                    console.log(response);
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
            event.preventDefault();
        });
    });
    //});
</script>

</body>
</html>